In [19]:
import netCDF4 as nc
import numpy as np


In [20]:
# read netcdf file
model_file = r"Z:\Thesis\Data\Met\ERA5\1984\United Arab Emirates\surface\1984_United Arab Emirates_surface_evaporation.nc"

In [21]:
ncfile = nc.Dataset(model_file,'r')
print(type(ncfile))

OSError: [Errno -101] NetCDF: HDF error: 'Z:\\Thesis\\Data\\Met\\ERA5\\1984\\United Arab Emirates\\surface\\1984_United Arab Emirates_surface_evaporation.nc'

In [22]:
# show what variables are contained in the file
for v in ncfile.variables:
        print(v)

number
valid_time
pressure_level
latitude
longitude
expver
z


In [23]:
# Extract a specific variable
lon = ncfile.variables['longitude'][:].data
lat = ncfile.variables['latitude'][:].data
time = ncfile.variables['time'][:].data
#d2m = ncfile.variables['d2m'][:].data
z = ncfile.variables['z'][:].data
level = ncfile.variables['level'][:].data
#number = ncfile.variables['number'][:].data
#expver = ncfile.variables['expver'][:].data
#t2m = ncfile.variables['t2m'][:].data

KeyError: 'time'

In [6]:
print(level, z)

[1000  925  850  700  500  300  200  100   50   10] [[[[  1347.96349423]
   [  1352.66313289]
   [  1352.66313289]]

  [[  8035.54930173]
   [  8035.54930173]
   [  8040.24894038]]

  [[ 15183.69969751]
   [ 15183.69969751]
   [ 15188.39933616]]

  ...

  [[162122.60191615]
   [162160.19902539]
   [162197.79613464]]

  [[201355.18541647]
   [201359.88505513]
   [201364.58469378]]

  [[302712.29231052]
   [302735.7905038 ]
   [302763.98833574]]]


 [[[  1390.26024214]
   [  1390.26024214]
   [  1390.26024214]]

  [[  8068.44677232]
   [  8068.44677232]
   [  8073.14641097]]

  [[ 15216.5971681 ]
   [ 15221.29680676]
   [ 15221.29680676]]

  ...

  [[162117.90227749]
   [162155.49938674]
   [162188.39685733]]

  [[201303.48939126]
   [201312.88866857]
   [201317.58830722]]

  [[302533.70604159]
   [302557.20423487]
   [302580.70242815]]]


 [[[  1550.04795644]
   [  1550.04795644]
   [  1550.04795644]]

  [[  8209.435932  ]
   [  8214.13557065]
   [  8223.53484797]]

  [[ 15357.58632778]

In [ ]:
print(z)

In [ ]:
print(lon)

In [ ]:
print(lat)

In [ ]:
print(time)

In [ ]:
print(number)

In [ ]:
print(expver)

In [ ]:
print(d2m)